### ISSUE TITLE
Sync issue

### ISSUE THREAD

**Issue by BK0STAR** [BharatKalluri/harmony#12]
Working good last week but it stop working.

```
[bkstar:~]$ harmony                     
Found 0 entries online
Found 10010 entries locally
Merged and Uploading 10010 entries, found 0 common
panic: Writing history to gist has failed!

goroutine 1 [running]:
main.initiateSync({0x1400013d3f0, 0x3})
	/Users/bkstar/go/pkg/mod/github.com/bharatkalluri/harmony@v0.1.1/main.go:46 +0x3cc
main.main()
	/Users/bkstar/go/pkg/mod/github.com/bharatkalluri/harmony@v0.1.1/main.go:62 +0xe4
```

**Comment by BharatKalluri** [comment]
Thanks for reporting the issue!

This could happen if the token is incorrect or the file does not exist. Can you double check once?
